Repository cloud-native-toolkit/terraform-aws-vpc, pull requests merged in 2022-05, with the labels that each got.

#14 Fix acl issue
  main.tf
Labels: bug, minor

#18 Module update
  module.yaml
Labels: bug, enhancement, patch

#19 BOM dependency update
  main.tf
  module.yaml
  variables.tf
Labels: patch, aws
